version: '3'

tasks:
  build:
    cmds:
      - docker-compose -f docker/docker-compose.yml build --no-cache
  up:
    cmds:
      - docker-compose -f docker/docker-compose.yml up -d
  down:
    cmds:
      - docker-compose -f docker/docker-compose.yml down
  proto-gen:
    cmds:
      - task: proto-gen-go
      - task: proto-gen-python
  proto-gen-go:
    cmds:
      - >
        docker-compose -f docker/docker-compose.yml run --rm protoc-go bash -c "
        protoc
        --go_out=./src/go
        --go_opt=paths=source_relative
        --go-grpc_out=./src/go
        --go-grpc_opt=paths=source_relative
        --go-grpc_opt=require_unimplemented_servers=false
        ./proto/*.proto"
  proto-gen-python:
    cmds:
      - >
        docker-compose -f docker/docker-compose.yml run --rm protoc-python bash -c "
        python -m grpc_tools.protoc
        --proto_path=.
        --python_out=./src/python
        --pyi_out=./src/python
        --grpc_python_out=./src/python
        ./proto/*.proto"
