version: "3"
services:
  protoc-go:
    build:
      context: ../
      dockerfile: ./docker/go/Dockerfile
    environment:
      - TZ=Asia/Tokyo
    working_dir: /home/src/go
    volumes:
      - ..:/home
    tty: true
  protoc-python:
    build:
      context: ../
      dockerfile: ./docker/python/Dockerfile
    environment:
      - TZ=Asia/Tokyo
    working_dir: /home/src/python
    volumes:
      - ..:/home
    tty: true