# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x06PinPon\"\x1e\n\rpinPonRequest\x12\r\n\x05words\x18\x01 \x01(\t\"\x1f\n\x0epinPonResponse\x12\r\n\x05words\x18\x01 \x01(\t2F\n\rPinPonService\x12\x35\n\x04send\x12\x15.PinPon.pinPonRequest\x1a\x16.PinPon.pinPonResponseB\x16Z\x14./go-protocol-bufferb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\024./go-protocol-buffer'
  _globals['_PINPONREQUEST']._serialized_start=24
  _globals['_PINPONREQUEST']._serialized_end=54
  _globals['_PINPONRESPONSE']._serialized_start=56
  _globals['_PINPONRESPONSE']._serialized_end=87
  _globals['_PINPONSERVICE']._serialized_start=89
  _globals['_PINPONSERVICE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
